/*
* Copyright (c) 2026 Contributors to the Eclipse Foundation.
*
* This program and the accompanying materials are made
* available under the terms of the Eclipse Public License 2.0
* which is available at https://www.eclipse.org/legal/epl-2.0/
*
* SPDX-License-Identifier: EPL-2.0
*
* Contributors:
*   Stefan Bischof (bipolis.org) - initial
*/
package org.eclipse.daanse.rolap.integration;

import static org.assertj.core.api.Assertions.assertThat;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Optional;

import org.eclipse.daanse.mdx.model.api.expression.operation.OperationAtom;
import org.eclipse.daanse.olap.api.DataType;
import org.eclipse.daanse.olap.api.function.FunctionMetaData;
import org.eclipse.daanse.olap.api.function.FunctionParameter;
import org.eclipse.daanse.olap.api.function.FunctionService;
import org.eclipse.daanse.olap.function.core.FunctionPrinter;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.osgi.test.common.annotation.InjectService;
import org.osgi.test.junit5.context.BundleContextExtension;

/**
 * Dumps every {@link FunctionMetaData} the running framework has registered
 * into a Markdown catalog. Everything the metadata can express is written out
 * - operation atom, interface, origin, calling object, arity window, return
 * type and the full parameter table including the optional/repeatable/
 * repeatGroup/skippable flags, reserved words and descriptions.
 *
 * Runs in the rolap test runtime because that is where the complete function
 * set is registered: the resolvers from olap.common plus the ones contributed
 * by rolap.core itself (Intersect, VisualTotals).
 */
@ExtendWith(BundleContextExtension.class)
class FunctionCatalogMarkdownTest {

    private static final Path OUTPUT = Path.of("target", "generated-docs", "mdx-function-catalog.md");

    @Test
    void writeFunctionCatalog(@InjectService FunctionService functionService) throws Exception {
        List<FunctionMetaData> all = functionService.getFunctionMetaDatas();
        assertThat(all).isNotEmpty();

        List<FunctionMetaData> sorted = new ArrayList<>(all);
        sorted.sort(Comparator.comparing((FunctionMetaData f) -> f.operationAtom().name(), String.CASE_INSENSITIVE_ORDER)
                .thenComparing(f -> f.operationAtom().getClass().getSimpleName())
                .thenComparing(FunctionMetaData::minArity));

        String markdown = render(sorted, functionService);

        Files.createDirectories(OUTPUT.getParent());
        Files.writeString(OUTPUT, markdown);

        assertThat(OUTPUT).exists();
        assertThat(Files.readString(OUTPUT)).contains("| Sum |").contains("Intersect").contains("VisualTotals");
    }

    private String render(List<FunctionMetaData> functions, FunctionService functionService) {
        StringBuilder sb = new StringBuilder();

        sb.append("# MDX function catalog\n\n");
        sb.append("Generated by `").append(getClass().getSimpleName())
                .append("` from the live `FunctionService` - do not edit by hand.\n\n");
        sb.append("- registered metadata entries: **").append(functions.size()).append("**\n");
        sb.append("- distinct function names: **")
                .append(functions.stream().map(f -> f.operationAtom().name()).distinct().count()).append("**\n");
        sb.append("- registered resolvers: **").append(functionService.getResolvers().size()).append("**\n");
        sb.append("- reserved property words: **").append(functionService.getPropertyWords().size()).append("**\n\n");

        appendOverview(sb, functions);
        appendDetails(sb, functions);
        appendGaps(sb, functions);

        return sb.toString();
    }

    private void appendOverview(StringBuilder sb, List<FunctionMetaData> functions) {
        sb.append("## Overview\n\n");
        sb.append("| Name | Atom | Interface | Origin | Returns | Arity | Signature |\n");
        sb.append("|---|---|---|---|---|---|---|\n");
        for (FunctionMetaData f : functions) {
            sb.append("| ").append(cell(f.operationAtom().name())) //
                    .append(" | ").append(atomKind(f.operationAtom())) //
                    .append(" | ").append(f.functionInterface()) //
                    .append(" | ").append(f.origin()).append(" (").append(f.origin().getValue()).append(")") //
                    .append(" | ").append(f.returnCategory()) //
                    .append(" | ").append(arity(f)) //
                    .append(" | ").append(cell(FunctionPrinter.getSignature(f))) //
                    .append(" |\n");
        }
        sb.append("\n");
    }

    private void appendDetails(StringBuilder sb, List<FunctionMetaData> functions) {
        sb.append("## Details\n\n");
        for (FunctionMetaData f : functions) {
            sb.append("### ").append(f.operationAtom().name()).append(" — ").append(atomKind(f.operationAtom()))
                    .append("\n\n");
            sb.append(f.description() == null || f.description().isBlank() ? "_no description_" : f.description())
                    .append("\n\n");

            sb.append("| Property | Value |\n|---|---|\n");
            row(sb, "Signature", FunctionPrinter.getSignature(f));
            row(sb, "Caption", f.caption());
            row(sb, "Text key", f.textKey());
            row(sb, "Operation atom", f.operationAtom().getClass().getSimpleName());
            row(sb, "Interface", String.valueOf(f.functionInterface()));
            row(sb, "Origin", f.origin() + " (" + f.origin().getValue() + ")");
            row(sb, "Library", f.libraryName().orElse("—"));
            row(sb, "Calling object", f.callingObject().map(Object::toString).orElse("—"));
            row(sb, "Return category", String.valueOf(f.returnCategory()));
            row(sb, "Arity", arity(f));
            row(sb, "Parameter types", typeList(f.parameterDataTypes()));
            row(sb, "DirectQuery pushable", String.valueOf(f.directQueryPushable()));
            row(sb, "Visual calculations info", String.valueOf(f.visualCalculationsInfo()));
            sb.append("\n");

            appendParameters(sb, f.parameters());
        }
    }

    private void appendParameters(StringBuilder sb, FunctionParameter[] parameters) {
        if (parameters == null || parameters.length == 0) {
            sb.append("_no parameters_\n\n");
            return;
        }
        sb.append("| # | Name | Type | Optional | Repeatable | Repeat group | Skippable | Reserved words |")
                .append(" Description |\n");
        sb.append("|---|---|---|---|---|---|---|---|---|\n");
        for (int i = 0; i < parameters.length; i++) {
            FunctionParameter p = parameters[i];
            sb.append("| ").append(i + 1) //
                    .append(" | ").append(cell(p.name().orElse("—"))) //
                    .append(" | ").append(p.dataType()) //
                    .append(" | ").append(flag(p.optional())) //
                    .append(" | ").append(flag(p.repeatable())) //
                    .append(" | ").append(p.repeatGroup() == 0 ? "—" : String.valueOf(p.repeatGroup())) //
                    .append(" | ").append(flag(p.skippable())) //
                    .append(" | ").append(cell(p.reservedWords().map(w -> String.join(", ", w)).orElse("—"))) //
                    .append(" | ").append(cell(p.description().orElse("—"))) //
                    .append(" |\n");
        }
        sb.append("\n");
    }

    /** What is still undocumented - the working list for the metadata sweep. */
    private void appendGaps(StringBuilder sb, List<FunctionMetaData> functions) {
        List<String> unnamed = new ArrayList<>();
        List<String> undescribed = new ArrayList<>();
        for (FunctionMetaData f : functions) {
            FunctionParameter[] params = f.parameters();
            if (params == null) {
                continue;
            }
            for (FunctionParameter p : params) {
                String id = f.operationAtom().name() + " / " + p.dataType();
                if (p.name().map(String::isBlank).orElse(true)) {
                    unnamed.add(id);
                }
                if (p.description().map(String::isBlank).orElse(true)) {
                    undescribed.add(id);
                }
            }
        }

        sb.append("## Metadata gaps\n\n");
        sb.append("- parameters without a name: **").append(unnamed.size()).append("**\n");
        sb.append("- parameters without a description: **").append(undescribed.size()).append("**\n\n");
        if (!unnamed.isEmpty()) {
            sb.append("Unnamed parameters:\n\n");
            unnamed.stream().distinct().sorted().forEach(s -> sb.append("- ").append(s).append("\n"));
            sb.append("\n");
        }
    }

    private void row(StringBuilder sb, String key, String value) {
        sb.append("| ").append(key).append(" | ").append(cell(value)).append(" |\n");
    }

    private String arity(FunctionMetaData f) {
        int max = f.maxArity();
        return f.minArity() + ".." + (max == Integer.MAX_VALUE ? "n" : String.valueOf(max));
    }

    private String typeList(DataType[] types) {
        if (types == null || types.length == 0) {
            return "—";
        }
        return String.join(", ", java.util.Arrays.stream(types).map(String::valueOf).toList());
    }

    private String atomKind(OperationAtom atom) {
        String simple = atom.getClass().getSimpleName();
        return simple.endsWith("OperationAtom") ? simple.substring(0, simple.length() - "OperationAtom".length())
                : simple;
    }

    private String flag(boolean value) {
        return value ? "yes" : "—";
    }

    /** Markdown cells must not break the table on pipes or line breaks. */
    private String cell(String value) {
        return Optional.ofNullable(value).orElse("—").replace("|", "\\|").replace("\r", " ").replace("\n", " ");
    }
}
